apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hello-world
  template:
    metadata:
      labels:
        service: hello-world
    spec:
      containers:
        - name: hello-world-service
          image: chadakrishnakrupa/my-image:main
          imagePullPolicy: Always
          env:
            #username
            - name: env.username
              valueFrom:
                configMapKeyRef:
                  name: myconfigmap
                  key: username
---
apiVersion: v1
kind: Service
metadata:
  name: service-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    service: hello-world
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001
